api/urls.py
from django.conf.urls import url, include
from api import views

urlpatterns = [
    url(r'^caca/$',  views.temp_list, name='temp_list'),
    url(r'^caca/(?P<sensor_id>[0-9]+)$', views.temp_detail, name='temp_detail'),
]

monitor/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # /monitor/
    url(r'^$', views.index, name='index'),

    # /monitor/sensor
    url(r'^(?P<sensor_id>[0-9]+)/$', views.detail, name='detail'),

    # chart
    url(r'^chart/$', views.chart, name='chart'),

    # bhart
    url(r'^bhart/$', views.chart, name='bhart'),

    # Sensors
    url(r'^sensors/$', views.sensors, name='sensors'),

    # thermostat
    url(r'^thermostat/$', views.thermostat, name='thermostat'),

    # Sensor Add
    url(r'^sensors/add/$', views.sensoradd, name='sensors-add'),

]

temon/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls')),
    url(r'^monitor/', include('monitor.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

monitor/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


# Create your models here.
class Sensor(models.Model):
    name = models.CharField(max_length=250)
    location = models.CharField(max_length=50)
    sensor_ip = models.GenericIPAddressField(protocol='IPv4')
    sensor_model = models.CharField(max_length=90)
    picture = models.CharField(max_length=1000)
    current_temperature = models.FloatField(max_length=100)

    def get_absolute_url(self):
        return reverse('monitor:detail', kwargs={'pk' : self.pk})

    def __str__(self):
        return self.name + ' - ' + self.sensor_model + ' --------- ' + str(self.current_temperature) + ' grade'

class Values(models.Model):
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)
    temperature = models.FloatField(max_length=100)
    time = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return str(self.temperature) + ' ' +  str(self.time)

    class Meta:
        get_latest_by = 'time'

class Thermostat(models.Model):
    temperature = models.FloatField(max_length=100)

    def __str__(self):
        return str(self.temperature)

monitor/forms.py
from django import forms
from monitor.models import Thermostat

class Tedit(forms.ModelForm):

    class Meta:
        model = Thermostat
        fields = ('temperature',)

monitor/views.py
from django.http import Http404
from django.shortcuts import render, render_to_response, redirect
from django.db.models import Q
from .models import Sensor, Values, Thermostat
from .forms import Tedit
from chartit import DataPool, Chart
from monitor.models import Values
from monitor.models import Thermostat
from datetime import datetime, timedelta
from .fusioncharts import FusionCharts
from  django.views.generic import CreateView, UpdateView, DeleteView

#from .decorators import add_source_code_and_doc


def index(request):
    all_sensors = Sensor.objects.all()
#   all_values = []

#    def sf():
#    for sensoir in all_sensors:
#        caca = Values.objects.filter(id__exact=sensoir.id).order_by('-id')[0]
#        all_values.append(caca.temperature)


    all_values = Values.objects.all()


    return render(request, 'monitor/index.html', {'all_sensors' : all_sensors, 'all_values' : all_values})

def detail(request, sensor_id):
    try:
        sensor = Sensor.objects.get(pk=sensor_id)
    except Sensor.DoesNotExist:
        raise Http404("INEXISTENT")
    return render(request, 'monitor/detail.html', {'sensor' : sensor})

def sensors(request):
    all_sensors = Sensor.objects.all()
    return render(request, 'monitor/sensors.html', {'all_sensors' : all_sensors})


"""
The chart part starts here
"""
def weather_chart_view(request):
    time_24_hours_ago = datetime.now() - timedelta(days=1)
    time_10_minutes_ago = datetime.now() - timedelta(minutes=10)
    #Step 1: Create a DataPool with the data we want to retrieve.
    weatherdata = \
        DataPool(
           series=
            [{'options': {
               'source': Values.objects.filter(time__gte=time_24_hours_ago).filter(Q(time__minute=00)).filter(sensor_id__exact=3)},

              'terms': [
                'time',
                'temperature']},
             ],

        )

    #Step 2: Create the Chart object
    cht = Chart(
            datasource = weatherdata,
            series_options =
              [{'options':{
                  'type': 'spline',
                  'lineWidth' : 3,

                  'stacking': True},
                'terms':{
                  'time': [
                    'temperature']
                  }}],
            chart_options =
              {'title': {
                   'text': 'Graficele de temperatura'},
               'xAxis': {
                    'title': {
                       'text': 'Ora'}}})

    #Step 3: Send the chart object to the template.
    return render_to_response('monitor/chart.html', {'wchart' : cht})


def chart(request):
    time_24_hours_ago = datetime.now() - timedelta(days=1)
    dataSource = {}
    dataSource1 = {}
    dataSource2 = {}

    #seriesname = []
    dataSource['chart'] = [{
        "caption": "Temperatures",
        "subCaption": "24 hours temperaturess",
        "captionPadding": "15",
        "xaxisname": "Ora",
        "yaxisname": "Temperatura",
        "showvalues": "0",
        "showLegend" : "1",
        "valueFontColor": "#ffffff",
        "placevaluesInside": "1",
        "usePlotGradientColor": "0",
        "legendShadow": "1",
        "showXAxisLine": "1",
        "xAxisLineColor": "#999999",
        "divlineColor": "#999999",
        "divLineIsDashed": "1",
        "showAlternateVGridColor": "0",
        "alignCaptionWithCanvas": "0",
        "legendPadding": "15",
        "drawCrossLine": "0",
        "palettecolors": "#f8bd19,#e44a00,#33bdda,#008ee4,#6baa01,#583e78",
        "plotToolText": "<div>Ora:<b>$label:00</b><br/>Temperatura : <b>$value grade</b></div>",
        "theme": "fint"
    }]
    lst = []
    for k in range(1, 25):
        caca = (datetime.now() + timedelta(hours=k))
        ch = float(caca.hour)
        lst.append({'label': ch})

    dataSource['categories'] = [{
        "category": lst
    }]


    dataSource1['data'] = []
    dataSource2['data'] = []
    dataSource['dataset'] = []

    for key in Values.objects.filter(time__gte=time_24_hours_ago).filter(Q(time__minute=00)).filter(sensor_id__exact=1):
        data = {}
        data['label'] = str(key.time)
        data['value'] = key.temperature
        dataSource1['data'].append(data)

    for key2 in Values.objects.filter(time__gte=time_24_hours_ago).filter(Q(time__minute=00)).filter(sensor_id__exact=3):
        data2 = {}
        data2['label'] = str(key2.time)
        data2['value'] = key2.temperature
        dataSource2['data'].append(data2)

    d1 = { "data" : dataSource1['data']}
    d2 = { "data" : dataSource2['data']}
    d3 = {"seriesname": "Birou"}
    d4 = {"seriesname": "Exterior"}

    dataSource['dataset'].append(d3)
    dataSource['dataset'].append(d1)
    dataSource['dataset'].append(d4)
    dataSource['dataset'].append(d2)


    # returning complete JavaScript and HTML code, which is used to generate chart in the browsers.
    # Create an object for the column2d chart using the FusionCharts class constructor
    column2d = FusionCharts("msspline", "ex1", "700", "300", "chart-1", "json", dataSource)
#    return render_to_response('monitor/bhart.html', {'output' : column2d.render()})
    return render(request, 'monitor/chart.html', {'output' : column2d.render()})

def thermostat(request):
    if request.method == 'POST':
        form = Tedit(request.POST)

        if form.is_valid():
            post = form.save(commit=True)
            post.save
            return redirect('thermostat')
        else:
            print(form.errors)

    else:
        form = Tedit()
    return render(request, 'monitor/thermostat.html', {'form' : form})

def sensoradd(CreateView):
    model = Sensor
    fields = ['name', 'location', 'sensor_ip', 'sensor_model', 'picture']

monitor/templates/monitor/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}Temon{% endblock %}</title>
</head>
<body>

<!-- loads the path to static css -->
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'js/bootstrap/css/bootstrap.min.css' %}">
<link href="https://fonts.googleapis.com/css?family=Days One" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'monitor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/flipclock/flipclock.css' %}">
<script src="{% static 'js/jquery/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/flipclock/flipclock.js' %}"></script>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}" style="color:red">Temon</a>
        </div>

        <!-- Buttons and Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'sensors'%}">
                        <span class="glyphicon glyphicon-scale" aria-hidden="true"></span>&nbsp
                        Sensors
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'chart' %}">
                        <span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span>&nbsp
                        Charts
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'thermostat'%}">
                        <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>&nbsp
                        Thermostat
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'index'%}">
                        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp
                        Schedule
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="clock" style="margin:0em;">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"><script type="text/javascript">
			var clock;

			$(document).ready(function() {
				clock = $('.clock').FlipClock({
					clockFace: 'TwentyFourHourClock',
					showSeconds: false
				});
			});
		</script></span>&nbsp

                    </a>
                </li>
                <li class="">
                    <a href="{% url 'sensors-add'%}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
                        Add Sensor
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'index'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
                        Logout
                    </a>
                </li>
            </ul>



        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

monitor/templates/monitor/bhart.html
{% extends 'monitor/base.html' %}


{% block body %}
{% load static %}



<!DOCTYPE html>
<html>
<head>
	<title>FC-python wrapper</title>
	{% load static %}
   <script type="text/javascript" src="{% static 'js/fusioncharts/fusioncharts.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/fusioncharts/themes/fusioncharts.theme.fint.js' %}"></script>
</head>
<body>
	<div id="chart-1">{{ output|safe }}</div>
</body>
</html>

<li>ORA ESTE {% now "SHORT_DATETIME_FORMAT" %}</li>
{% endblock %}


monitor/templates/monitor/chart.html
{% extends 'monitor/base.html' %}


{% block body %}
{% load static %}



<!DOCTYPE html>
<html>
<head>
	<title>FC-python wrapper</title>
	{% load static %}
   <script type="text/javascript" src="{% static 'js/fusioncharts/fusioncharts.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/fusioncharts/themes/fusioncharts.theme.fint.js' %}"></script>
</head>
<body>
	<div id="chart-1">{{ output|safe }}</div>
</body>
</html>

<li>ORA ESTE {% now "SHORT_DATETIME_FORMAT" %}</li>
{% endblock %}


monitor/templates/monitor/detail.html
{% extends 'monitor/base.html' %}
{% block title%}Sensor Detail{% endblock %}

{% block body %}
{{ sensor }}
{% endblock %}

monitor/templates/monitor/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

monitor/templates/monitor/index.html
{% extends 'monitor/base.html' %}




{% block body %}
{% if all_sensors %}
<div class="row-md-4">
    <h4>Sensor list:</h4>
</div>
<div class="container-fluid ">
    <div class="row">
        <div class="col-md-4">


{% load staticfiles %}
<script src="{% static 'js/justgauge/raphael-2.1.4.min.js' %}"></script>
<script src="{% static 'js/justgauge/justgage.js' %}"></script>

{% for sensor in all_sensors %}

    <div class="container-fluid ">
    <div id="g{{ sensor.id}}" class="col-xs-6 col-md-4">
    </div>
  </div>
<script>
    var g{{ sensor.id}};
    document.addEventListener("DOMContentLoaded", function(event) {
        g1 = new JustGage({
            id: "g{{ sensor.id}}",
            title: "{{ sensor.name }}",
            value: {{ sensor.values_set.latest.temperature }},
            decimals: 2,
            symbol: '˚',
            min: 0,
            max: 50,
            donut: true,
            gaugeWidthScale: 0.9,
            counter: true,
            hideInnerShadow: false
        });

        document.getElementById('g1_refresh').addEventListener('click', function() {
            g1.refresh(getRandomInt(0, 100));
        });
    });
    </script>
    {% endfor %}

        </div>
    </div>
</div>
<!--
    <ul>
        {% for sensor in all_sensors %}
        <li><a href="/monitor/{{ sensor.id}}"> {{ sensor.name }} -  {{ sensor.id }} -  {{ sensor.values_set.latest.temperature }}
        </a> </li>
        {% endfor %}

    </ul>
-->
{% else %}
    <h3>No Sensors detected</h3>
{% endif %}

{% endblock %}

monitor/templates/monitor/sensors.html
{% extends 'monitor/base.html' %}

{% block body %}
{% if all_sensors %}
<div class="row-md-4">
    <h4>Sensor list: </h4>
</div>
<div class="container-fluid ">
    <div class="row">
        <div class="col-md-4">


    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Sensor IP</th>
                <th>Sensor Model</th>
                <th>Sensor Picture</th>
            </tr>
        </thead>
        <tbody>
        {% for sensor in all_sensors %}
            <tr>
                <td>{{ sensor.id }}</td>
                <td>{{ sensor.name }}</td>
                <td>{{ sensor.sensor_ip }}</td>
                <td>{{ sensor.sensor_model }}</td>
                <td><img src="{{ sensor.picture }}" height="50" width="50"  ></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        </div>
    </div>
</div>

{% else %}
    <h3>No Sensors detected</h3>
{% endif %}

{% endblock %}

monitor/templates/monitor/sensors_form.html
{% extemds 'monitor/base.html' %}
{% block title%}Add a new sensor {% endblock %}



{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel-body">
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'monitor/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

{% endblock %}


monitor/templates/monitor/thermostat.html
{% extends 'monitor/base.html' %}
{% block title%}Sensor Detail{% endblock %}

{% block body %}
<p>

         <h1>New post</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>



</p>
{% endblock %}